#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Models;
using MVZ2Logic.Models;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Enemies
{
    /// <summary>
    /// WitherHeartShieldResistanceBuff��
    /// ֻ�ṩ�˺�����Ч�����ҵ����ﴦ�ڹ���״̬ʱ������
    /// �������κ��Ӿ����黯����
    /// </summary>
    [BuffDefinition(VanillaBuffNames.Enemy.WitherHeartShieldResistanceBuff)]
    public class WitherHeartShieldResistanceBuff : BuffDefinition
    {
        public WitherHeartShieldResistanceBuff(string nsp, string name) : base(nsp, name)
        {
            // ע��ʵ������ǰ�Ļص�������ʵ�ּ��˻���
            AddTrigger(VanillaLevelCallbacks.PRE_ENTITY_TAKE_DAMAGE, PreEntityTakeDamageCallback);
            AddModelInsertion(LogicModelHelper.ANCHOR_CENTER, VanillaModelKeys.ResistanceShield, VanillaModelID.ResistanceShield);

        }

        /// <summary>
        /// �˺�ǰ�ص����ж��Ƿ�ӵ�и�Buff���ҹ���ǹ���״̬ʱӦ�ü��˱���
        /// </summary>
        private void PreEntityTakeDamageCallback(VanillaLevelCallbacks.PreTakeDamageParams param, CallbackResult callbackResult)
        {
            var damageInfo = param.input;
            var entity = damageInfo.Entity;

            if (entity == null)
                return;

            // 没有护心盾buff的怪物不触发。
            var buffCount = entity.GetBuffCount<WitherHeartShieldResistanceBuff>();
            if (buffCount == 0)
                return;

            var multiplier = 1f;
            // 己方怪物受到75%额外伤害。
            if (entity.IsFriendlyEntity())
            {
                multiplier *= 1.75f;
            }

            // 非飞行怪物受到的伤害减少75%。
            if (entity.IsHostileEntity() && !entity.HasBuff<FlyBuff>())
            {
                multiplier *= 0.25f;
                // 但在攻击时额外受到25%额外伤害。
                if (entity.State == STATE_MELEE_ATTACK)
                {
                    multiplier *= 1.25f;
                }
            }

            // 每有一个护心盾buff，额外乘一次。
            damageInfo.Multiply(Mathf.Pow(multiplier, buffCount));
        }

        // �������б������ÿ�η��䣬��������
        private List<Buff> buffBuffer = new List<Buff>();
        public const int STATE_MELEE_ATTACK = VanillaEnemyStates.MELEE_ATTACK;
    }
}
