#nullable enable // autogenerated

using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Obstacles;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Buffs;

namespace MVZ2.GameContent.Obstacles
{
    /// <summary>
    /// 鱿鱼笼行为 - 敌方障碍物，被摧毁时复原被困的器械
    /// </summary>
    [EntityBehaviourDefinition(VanillaObstacleNames.SquidCage)]
    public class SquidCageBehaviour : ObstacleBehaviour
    {
        public SquidCageBehaviour(string nsp, string name) : base(nsp, name)
        {
        }

        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);

            // 获取被囚禁的器械 ID 并复原
            var trappedPlantID = entity.GetProperty<EntityID>(PROP_TRAPPED_PLANT_ID);
            if (trappedPlantID != null)
            {
                var level = entity.Level;
                var trappedPlant = trappedPlantID.GetEntity(level);
                if (trappedPlant != null && trappedPlant.Exists())
                {
                    // 移除器械上的 SquidDrownedMarkedBuff（这会恢复器械）
                    var markBuff = trappedPlant.GetFirstBuff<SquidDrownedMarkedBuff>();
                    if (markBuff != null)
                    {
                        markBuff.Remove();
                    }
                    else
                    {
                        // 如果没有 buff，直接恢复器械状态
                        trappedPlant.SetNeutralized(false);
                    }
                }
            }

            // 移除障碍物实体（确保消失）
            entity.Remove();
        }

        public static void SetTrappedPlantID(Entity cage, EntityID plantID)
        {
            cage.SetProperty(PROP_TRAPPED_PLANT_ID, plantID);
        }

        public static readonly VanillaEntityPropertyMeta<EntityID> PROP_TRAPPED_PLANT_ID = new VanillaEntityPropertyMeta<EntityID>("trappedPlantId");
    }
}
