#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs
{
    /// <summary>
    /// 鱿鱼溺尸标记 - 让器械休眠，被鱿鱼笼替代
    /// 器械会被双方无视（无法被攻击）
    /// </summary>
    [BuffDefinition(VanillaBuffNames.Entity.squidDrownedMarked)]
    public class SquidDrownedMarkedBuff : BuffDefinition
    {
        public SquidDrownedMarkedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(VanillaEntityProps.AI_FROZEN, true));
            // 让器械被所有碰撞检测忽略（双方无视）
            AddModifier(new IntModifier(EngineEntityProps.COLLISION_DETECTION, IntegerOperator.Set, EntityCollisionHelper.DETECTION_IGNORE));
        }

        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            var entity = buff.GetEntity();
            if (entity == null)
                return;

            // 标记为 Neutralized（怪物会无视它）
            entity.SetNeutralized(true);

            // 添加 StunBuff（眩晕效果）
            var stunBuff = entity.AddBuff<StunBuff>();
            if (stunBuff != null)
            {
                StunBuff.SetStunTime(stunBuff, MAX_STUN_TIME);
                buff.SetProperty(PROP_STUN_ENTITY_ID, stunBuff.ID.ToString());
            }
        }

        public override void PostRemove(Buff buff)
        {
            base.PostRemove(buff);
            var entity = buff.GetEntity();
            if (entity == null)
                return;

            // 恢复器械状态
            entity.SetNeutralized(false);

            // 移除关联的 StunBuff
            var stunID = buff.GetProperty<string>(PROP_STUN_ENTITY_ID);
            if (!string.IsNullOrEmpty(stunID))
            {
                foreach (var stun in entity.GetBuffs<StunBuff>())
                {
                    if (stun.ID.ToString() == stunID)
                    {
                        stun.Remove();
                        break;
                    }
                }
            }

            // 清理关联的障碍物（如果还存在）
            var cageID = buff.GetProperty<EntityID>(PROP_CAGE_ID);
            if (cageID != null)
            {
                var cage = cageID.GetEntity(buff.Level);
                if (cage != null && cage.Exists() && !cage.IsDead)
                {
                    cage.Remove();
                }
            }
        }

        public static bool IsMarked(Entity entity)
        {
            return entity.GetFirstBuff<SquidDrownedMarkedBuff>() != null;
        }

        public static void SetCageID(Buff buff, EntityID cageID)
        {
            buff.SetProperty(PROP_CAGE_ID, cageID);
        }

        public static readonly VanillaBuffPropertyMeta<EntityID> PROP_CAGE_ID = new VanillaBuffPropertyMeta<EntityID>("cageId");
        public static readonly VanillaBuffPropertyMeta<string> PROP_STUN_ENTITY_ID = new VanillaBuffPropertyMeta<string>("stunEntityId");

        public const int MAX_STUN_TIME = 180000;
    }
}
