#nullable enable // autogenerated

using MVZ2.Vanilla;
using PVZEngine;

namespace MVZ2.GameContent.Buffs
{
    public static class VanillaBuffNames
    {
        public static class Level
        {

            // Difficulty
            public const string levelEasy = "level_easy";
            public const string levelHard = "level_hard";
            public const string levellunatic = "level_lunatic";
            public const string iZombieEasy = "i_zombie_easy";
            public const string iZombieHard = "i_zombie_hard";
            public const string iZombieLunatic = "iZombieLunatic";

            // Debug
            public const string debugGodmode = "debug_godmode";
            public const string debugNoRecharge = "debug_no_recharge";
            public const string debugStarshard = "debug_starshard";
            public const string debugEnergy = "debug_energy";

            // Tutorial
            public const string tutorialPickaxeDisable = "tutorial_pickaxe_disable";
            public const string tutorialTriggerDisable = "tutorial_trigger_disable";

            // Chapter 1
            public const string swordParalyzed = "sword_paralyzed";
            public const string thunder = "thunder";
            public const string frankensteinStage = "frankenstein_stage";

            // Chapter 2
            public const string pagodaBranchLevel = "pagoda_branch_level";
            public const string darkMatterDark = "dark_matter_dark";
            public const string taintedSun = "tainted_sun";
            public const string nightmareLevel = "nightmare_level";
            public const string nightmareDecrepify = "nightmare_decrepify";
            public const string nightmareaperDarkness = "nightmareaper_darkness";
            public const string slendermanTransition = "slenderman_transition";
            public const string nightmareaperTransition = "nightmareaper_transition";
            public const string nightmareCleared = "nightmare_cleared";

            // Chapter 3
            public const string reverseSatellite = "reverse_satellite";
            public const string littleZombieLevel = "little_zombie_level";
            public const string seijaAutoCollect = "seija_auto_collect";
            public const string witherTransition = "wither_transition";
            public const string witherCleared = "wither_cleared";

            // Chapter 4
            public const string delayedSpawnerTrigger = "delayed_spawner_trigger";
            public const string spiritUniverseNight = "spirit_universe_night";
            public const string theGiantTransition = "the_giant_transition";
            public const string theGiantCleared = "the_giant_cleared";

            // Chapter 5
            public const string ufoSpawn = "ufo_spawn";
            public const string beaconMeteor = "beacon_meteor";
            public const string sorcerersScrollStarshard = "sorcerers_scroll_starshard";
            public const string skywardNight = "skyward_night";
            public const string redDragonStage = "red_dragon_stage";
            public const string redDragonTransition = "red_dragon_transition";
            public const string redDragonCleared = "red_dragon_cleared";

            // Random China
            public const string greedyVacuum = "greedy_vacuum";
            public const string superRecharge = "super_recharge";
            public const string ancientEgypt = "ancient_egypt";

            //EXPAND
            public const string slendermanBlackSun = "slendermanBlackSun";
        }
        public static class Grid
        {
            // Chapter 5
            public const string waterStainWet = "water_stain_wet";
            public const string goldenGrid = "golden_grid";
            public const string shipBrokenGrid = "ship_broken_grid";
        }
        public static class Entity
        {
            // Core
            public const string entityPhysics = "entity_physics";
            public const string faction = "faction";
            public const string changeLane = "change_lane";
            public const string changeGrid = "change_grid";
            public const string damageColor = "damage_color";
            public const string temporaryUpdateBeforeGame = "temporary_update_before_game";
            public const string destroyConflictGridEntitiesOnLand = "destroy_conflict_grid_entities_on_land";

            // Chapter 1
            public const string lightFadeout = "light_fadeout";

            // Chapter 2
            public const string inWater = "in_water";
            public const string whiteFlash = "white_flash";
            public const string parabot = "parabot";

            // Chapter 3
            public const string charm = "charm";
            public const string withered = "withered";

            // Chapter 4
            public const string divineShield = "divine_shield";
            public const string divineShieldCooldown = "divine_shield_cooldown";

            // Chapter 5
            public const string aboveCloud = "above_cloud";
            public const string dragonTooth = "dragon_tooth";
            public const string clearGridOnLand = "clear_grid_on_land";

            // Random China
            public const string worldwideCelebration = "worldwide_celebration";

            //EXPAND
            public const string Regeneration = "Regeneration";
            public const string Corropoison = "Corropoison";
            public const string Resistance = "Resistance";
            public const string ExplosionProtection = "ExplosionProtection";
            public const string DeathMark = "DeathMark";
            public const string squidDrownedMarked = "squid_drowned_marked";
        }
        public static class Armor
        {
            // Difficulty
            public const string easyArmor = "easy_armor";

            // Core
            public const string armorDamageColor = "armor_damage_color";

            // Chapter 3
            public const string littleZombieArmor = "little_zombie_armor";
            public const string bigTroubleArmor = "big_trouble_armor";

            // Chapter 4
            public const string iZombieSkeletonWarriorArmor = "i_zombie_skeleton_warrior_armor";
        }
        public static class Contraption
        {
            // Difficulty
            public const string easyContraption = "easy_contraption";

            // Prologue
            public const string obsidianArmor = "obsidian_armor";
            public const string mineTNTInvincible = "mine_tnt_invincible";
            public const string GlowingObsidianArmorBuff = "GlowingObsidianArmorBuff";

            // Chapter 1
            public const string moonlightSensorLaunching = "moonlight_sensor_launching";
            public const string moonlightSensorEvoked = "moonlight_sensor_evoked";
            public const string glowstoneEvoke = "glowstone_evoke";
            public const string tntIgnited = "tnt_ignited";
            public const string tntCharged = "tnt_charged";
            public const string sacrificed = "sacrificed";
            public const string magichestInvincible = "magichest_invincible";
            public const string frankensteinShocked = "frankenstein_shocked";
            public const string dreamKeyShield = "dream_key_shield";

            // Chapter 2
            public const string nocturnal = "nocturnal";
            public const string carriedByLilyPad = "carried_by_lily_pad";
            public const string carryingOther = "carrying_other";
            public const string lilyPadEvocation = "lily_pad_evocation";
            public const string dreamButterflyShield = "dream_butterfly_shield";
            public const string darkMatterProduction = "dark_matter_production";
            public const string vortexHopperSpin = "vortex_hopper_spin";
            public const string vortexHopperEvoked = "vortex_hopper_evoked";
            public const string dreamCrystalEvocation = "dream_crystal_evocation";
            public const string dreamSilk = "dream_silk";
            public const string bottledBlackholeDamage = "bottled_blackhole_damage";

            // Chapter 3
            public const string stoneShieldProtected = "stone_shield_protected";
            public const string glowstoneProtected = "glowstone_protected";
            public const string ironCurtain = "iron_curtain";
            public const string miracleMalletReplicaDamage = "miracle_mallet_replica_damage";
            public const string witherSkeletonSkullReduceHealth = "wither_skeleton_skull_reduce_health";
            public const string FrankensteinBrainAddHealthBuff = "FrankensteinBrainAddHealthBuff";
            public const string brokenLantern = "broken_lantern";

            // Chapter 4
            public const string eyeOfTheGiant = "eye_of_the_giant";
            public const string noteBlockLoud = "note_block_loud";
            public const string lightningOrbEvoked = "lightning_orb_evoked";
            public const string devourerInvincible = "devourer_invincible";
            public const string hellfireCursed = "hellfire_cursed";
            public const string imitated = "imitated";
            public const string noteBlockCharged = "note_block_charged";

            // Chapter 5
            public const string fireworkDispenserEvoked = "firework_dispenser_evoked";
            public const string hfpdUpgraded = "hfpd_upgraded";
            public const string stolenByUFO = "stolen_by_ufo";
            public const string woodenFanBlow = "wooden_fan_blow";
            public const string elasticCloudBounceCooldown = "elastic_cloud_bounce_cooldown";
            public const string elasticCloudEvocation = "elastic_cloud_evocation";
            public const string skywardBeaconNight = "skyward_beacon_night";

            //EXPAND
            public const string TeslaCoilOvercharge = "TeslaCoilOvercharge";
        }
        public static class Enemy
        {
            // Difficulty
            public const string hardEnemy = "hard_enemy";
            public const string lunaticEnemy = "lunaticEnemy";

            // Core
            public const string randomEnemySpeed = "random_enemy_speed";
            public const string VanguardResistance = "VanguardResistance";
            public const string WitherProtection = "WitherProtection";

            // Prologue
            public const string gemCarrier = "gem_carrier";

            // Chapter 1
            public const string punchtonAchievement = "punchton_achievement";
            public const string starshardCarrier = "starshard_carrier";
            public const string redstoneCarrier = "redstone_carrier";
            public const string ghost = "ghost";
            public const string stun = "stun";
            public const string minigameEnemySpeed = "minigame_enemy_speed";
            public const string napstablookAngry = "napstablook_angry";
            public const string frankensteinTransformer = "frankenstein_transformer";

            // Chapter 2
            public const string boat = "boat";
            public const string spiderClimb = "spider_climb";
            public const string motherTerrorLaid = "mother_terror_laid";
            public const string terrorParasitized = "terror_parasitized";
            public const string gravityPadGravity = "gravity_pad_gravity";
            public const string vortexHopperDrag = "vortex_hopper_drag";
            public const string fly = "fly";
            public const string enemyWeakness = "enemy_weakness";
            public const string forcePadDrag = "force_pad_drag";
            public const string nightmareComeTrue = "nightmare_come_true";
            public const string NightmareMaskEvade = "NightmareMaskEvade";
            public const string WitherHeartShieldResistanceBuff = "WitherHeartShieldResistanceBuff";
            public const string LeftHandBowBuff = "LeftHandBowBuff";

            // Chapter 3
            public const string littleZombie = "little_zombie";
            public const string bigTrouble = "big_trouble";
            public const string soulsandSummoned = "soulsand_summoned";
            public const string seijaMesmerizer = "seija_mesmerizer";
            public const string beingRiden = "being_riden";
            public const string ridingPassenger = "riding_passenger";

            // Chapter 4
            public const string wickedHermitWarp = "wicked_hermit_warp";
            public const string wickedHermitWarpped = "wicked_hermit_warpped";
            public const string necrotombstoneRising = "necrotombstone_rising";
            public const string slow = "slow";
            public const string iZombieAttackBooster = "i_zombie_attack_booster";
            public const string iZombieImp = "i_zombie_imp";
            public const string iZombieSkeletonWarrior = "i_zombie_skeleton_warrior";
            public const string shikaisenRevive = "shikaisen_revive";
            public const string SixQiResistanceBuff = "SixQiResistanceBuff";

            // Chapter 5
            public const string paratroop = "paratroop";
            public const string summonedByUFO = "summoned_by_ufo";
            public const string ufoBlueAbsorb = "ufo_blue_absorb";
            public const string heavyCannon = "heavy_cannon";
            public const string waterStainSlide = "water_stain_slide";
            public const string blownByWoodenFan = "blown_by_wooden_fan";



            //EXPAND
            public const string AntiGravityPadGravity = "AntiGravityPadGravity";
            public const string Shock = "Shock";
            public const string AttackSpeed = "AttackSpeed";
            public const string SoulFreeze = "SoulFreeze";

        }
        public static class Obstacle
        {
        }
        public static class Boss
        {
            public const string bossRevenge = "boss_revenge";

            // Chapter 1
            public const string frankensteinSteel = "frankenstein_steel";
            public const string frankensteinTransforming = "frankenstein_transforming";

            // Chapter 2
            public const string nightmareaperFall = "nightmareaper_fall";
            public const string nightmareaperEnraged = "nightmareaper_enraged";

            // Chapter 3
            public const string seijaFabric = "seija_fabric";
            public const string seijaGap = "seija_gap";

            // Chapter 4
            public const string theGiantInactive = "the_giant_inactive";
            public const string theGiantPacman = "the_giant_pacman";
            public const string theGiantPacmanKilled = "the_giant_pacman_killed";
            public const string theGiantSnake = "the_giant_snake";
            public const string theGiantPhase3 = "the_giant_phase3";
        }
        public static class Cart
        {
            // Prologue
            public const string cartFadeIn = "cart_fade_in";
        }
        public static class Pickup
        {
            // Chapter 5
            public const string absorbedByUFO = "absorbed_by_ufo";
        }
        public static class Projectile
        {
            // Chapter 1
            public const string projectileWait = "projectile_wait";

            // Chapter 2
            public const string projectileKnockback = "projectile_knockback";
            public const string ghastFireCharge = "ghast_fire_charge";

            // Chapter 3
            public const string invertedMirror = "inverted_mirror";

            // Chapter 4
            public const string hellfireIgnited = "hellfire_ignited";

            // Chapter 5
            public const string beaconMeteorNoDestroy = "beacon_meteor_no_destroy";
        }
        public static class Effect
        {
            // Chapter 2
            public const string breakoutBoardUpgrade = "breakout_board_upgrade";

            // Chapter 5
            public const string waterStainFrozen = "water_stain_frozen";
        }

        public static class SeedPack
        {
            // Difficulty
            public const string easyBlueprint = "easy_blueprint";

            // Stages
            public const string tutorialBlueprintDisable = "tutorial_blueprint_disable";
            public const string upgradeEndlessCost = "upgrade_endless_cost";

            // Chapter 1
            public const string theCreaturesHeartReduceCost = "the_creatures_heart_reduce_cost";

            // Chapter 2
            public const string slendermanMindSwap = "slenderman_mind_swap";

            // Chapter 3
            public const string witherSkeletonSkullReduceCost = "wither_skeleton_skull_reduce_cost";

            public const string FrankensteinBrainBuff = "FrankensteinBrainBuff";
        }
    }
    public static class VanillaBuffID
    {
        private static NamespaceID Get(string name)
        {
            return new NamespaceID(VanillaMod.spaceName, name);
        }
        public static class Level
        {
            // Difficulty
            public static readonly NamespaceID levelEasy = Get(VanillaBuffNames.Level.levelEasy);
            public static readonly NamespaceID levelHard = Get(VanillaBuffNames.Level.levelHard);
            public static readonly NamespaceID levellunatic = Get(VanillaBuffNames.Level.levellunatic);
            public static readonly NamespaceID iZombieEasy = Get(VanillaBuffNames.Level.iZombieEasy);
            public static readonly NamespaceID iZombieHard = Get(VanillaBuffNames.Level.iZombieHard);
            public static readonly NamespaceID iZombieLunatic = Get(VanillaBuffNames.Level.iZombieLunatic);

            // Debug
            public static readonly NamespaceID debugGodmode = Get(VanillaBuffNames.Level.debugGodmode);
            public static readonly NamespaceID debugNoRecharge = Get(VanillaBuffNames.Level.debugNoRecharge);
            public static readonly NamespaceID debugStarshard = Get(VanillaBuffNames.Level.debugStarshard);
            public static readonly NamespaceID debugEnergy = Get(VanillaBuffNames.Level.debugEnergy);

            // Tutorial
            public static readonly NamespaceID tutorialPickaxeDisable = Get(VanillaBuffNames.Level.tutorialPickaxeDisable);
            public static readonly NamespaceID tutorialTriggerDisable = Get(VanillaBuffNames.Level.tutorialTriggerDisable);

            // Chapter 1
            public static readonly NamespaceID swordParalyzed = Get(VanillaBuffNames.Level.swordParalyzed);
            public static readonly NamespaceID thunder = Get(VanillaBuffNames.Level.thunder);
            public static readonly NamespaceID frankensteinStage = Get(VanillaBuffNames.Level.frankensteinStage);

            // Chapter 2
            public static readonly NamespaceID pagodaBranchLevel = Get(VanillaBuffNames.Level.pagodaBranchLevel);
            public static readonly NamespaceID darkMatterDark = Get(VanillaBuffNames.Level.darkMatterDark);
            public static readonly NamespaceID taintedSun = Get(VanillaBuffNames.Level.taintedSun);
            public static readonly NamespaceID nightmareLevel = Get(VanillaBuffNames.Level.nightmareLevel);
            public static readonly NamespaceID nightmareDecrepify = Get(VanillaBuffNames.Level.nightmareDecrepify);
            public static readonly NamespaceID nightmareaperDarkness = Get(VanillaBuffNames.Level.nightmareaperDarkness);
            public static readonly NamespaceID slendermanTransition = Get(VanillaBuffNames.Level.slendermanTransition);
            public static readonly NamespaceID nightmareaperTransition = Get(VanillaBuffNames.Level.nightmareaperTransition);
            public static readonly NamespaceID nightmareCleared = Get(VanillaBuffNames.Level.nightmareCleared);

            // Chapter 3
            public static readonly NamespaceID reverseSatellite = Get(VanillaBuffNames.Level.reverseSatellite);
            public static readonly NamespaceID littleZombieLevel = Get(VanillaBuffNames.Level.littleZombieLevel);
            public static readonly NamespaceID seijaAutoCollect = Get(VanillaBuffNames.Level.seijaAutoCollect);
            public static readonly NamespaceID witherTransition = Get(VanillaBuffNames.Level.witherTransition);
            public static readonly NamespaceID witherCleared = Get(VanillaBuffNames.Level.witherCleared);

            // Chapter 4
            public static readonly NamespaceID delayedSpawnerTrigger = Get(VanillaBuffNames.Level.delayedSpawnerTrigger);
            public static readonly NamespaceID spiritUniverseNight = Get(VanillaBuffNames.Level.spiritUniverseNight);
            public static readonly NamespaceID theGiantTransition = Get(VanillaBuffNames.Level.theGiantTransition);
            public static readonly NamespaceID theGiantCleared = Get(VanillaBuffNames.Level.theGiantCleared);
            public static readonly NamespaceID greedyVacuum = Get(VanillaBuffNames.Level.greedyVacuum);

            // Chapter 5
            public static readonly NamespaceID ufoSpawn = Get(VanillaBuffNames.Level.ufoSpawn);
            public static readonly NamespaceID beaconMeteor = Get(VanillaBuffNames.Level.beaconMeteor);
            public static readonly NamespaceID sorcerersScrollStarshard = Get(VanillaBuffNames.Level.sorcerersScrollStarshard);
            public static readonly NamespaceID skywardNight = Get(VanillaBuffNames.Level.skywardNight);

            // Random China
            public static readonly NamespaceID superRecharge = Get(VanillaBuffNames.Level.superRecharge);
            public static readonly NamespaceID ancientEgypt = Get(VanillaBuffNames.Level.ancientEgypt);

            //EXPAND
            public static readonly NamespaceID slendermanBlackSun = Get(VanillaBuffNames.Level.slendermanBlackSun);
        }
        public static class Grid
        {
            // Chapter 5
            public static readonly NamespaceID waterStainWet = Get(VanillaBuffNames.Grid.waterStainWet);
            public static readonly NamespaceID goldenGrid = Get(VanillaBuffNames.Grid.goldenGrid);
            public static readonly NamespaceID shipBrokenGrid = Get(VanillaBuffNames.Grid.shipBrokenGrid);
        }
        public static class Entity
        {
            // Core
            public static readonly NamespaceID entityPhysics = Get(VanillaBuffNames.Entity.entityPhysics);
            public static readonly NamespaceID faction = Get(VanillaBuffNames.Entity.faction);
            public static readonly NamespaceID changeLane = Get(VanillaBuffNames.Entity.changeLane);
            public static readonly NamespaceID damageColor = Get(VanillaBuffNames.Entity.damageColor);
            public static readonly NamespaceID temporaryUpdateBeforeGame = Get(VanillaBuffNames.Entity.temporaryUpdateBeforeGame);
            public static readonly NamespaceID destroyConflictGridEntitiesOnLand = Get(VanillaBuffNames.Entity.destroyConflictGridEntitiesOnLand);
            
            public static readonly NamespaceID Regeneration = Get(VanillaBuffNames.Entity.Regeneration);
            public static readonly NamespaceID Corropoison = Get(VanillaBuffNames.Entity.Corropoison);
            public static readonly NamespaceID squidDrownedMarked = Get(VanillaBuffNames.Entity.squidDrownedMarked);
            public static readonly NamespaceID DeathMark = Get(VanillaBuffNames.Entity.DeathMark);

            // Chapter 2
            public static readonly NamespaceID inWater = Get(VanillaBuffNames.Entity.inWater);
            public static readonly NamespaceID whiteFlash = Get(VanillaBuffNames.Entity.whiteFlash);
            public static readonly NamespaceID parabot = Get(VanillaBuffNames.Entity.parabot);

            // Chapter 3
            public static readonly NamespaceID charm = Get(VanillaBuffNames.Entity.charm);
            public static readonly NamespaceID withered = Get(VanillaBuffNames.Entity.withered);

            // Chapter 4
            public static readonly NamespaceID divineShield = Get(VanillaBuffNames.Entity.divineShield);
            public static readonly NamespaceID divineShieldCooldown = Get(VanillaBuffNames.Entity.divineShieldCooldown);

            // Chapter 5
            public static readonly NamespaceID aboveCloud = Get(VanillaBuffNames.Entity.aboveCloud);
            public static readonly NamespaceID dragonTooth = Get(VanillaBuffNames.Entity.dragonTooth);

            // Random China
            public static readonly NamespaceID worldwideCelebration = Get(VanillaBuffNames.Entity.worldwideCelebration);
        }
        public static class Armor
        {
            // Difficulty
            public static readonly NamespaceID easyArmor = Get(VanillaBuffNames.Armor.easyArmor);

            // Core
            public static readonly NamespaceID armorDamageColor = Get(VanillaBuffNames.Armor.armorDamageColor);

            // Chapter 3
            public static readonly NamespaceID littleZombieArmor = Get(VanillaBuffNames.Armor.littleZombieArmor);
            public static readonly NamespaceID bigTroubleArmor = Get(VanillaBuffNames.Armor.bigTroubleArmor);

            // Chapter 4
            public static readonly NamespaceID iZombieSkeletonWarriorArmor = Get(VanillaBuffNames.Armor.iZombieSkeletonWarriorArmor);
        }
        public static class Contraption
        {
            // Difficulty
            public static readonly NamespaceID easyContraption = Get(VanillaBuffNames.Contraption.easyContraption);

            // Prologue
            public static readonly NamespaceID obsidianArmor = Get(VanillaBuffNames.Contraption.obsidianArmor);
            public static readonly NamespaceID mineTNTInvincible = Get(VanillaBuffNames.Contraption.mineTNTInvincible);

            // Chapter 1
            public static readonly NamespaceID moonlightSensorLaunching = Get(VanillaBuffNames.Contraption.moonlightSensorLaunching);
            public static readonly NamespaceID moonlightSensorEvoked = Get(VanillaBuffNames.Contraption.moonlightSensorEvoked);
            public static readonly NamespaceID glowstoneEvoke = Get(VanillaBuffNames.Contraption.glowstoneEvoke);
            public static readonly NamespaceID tntIgnited = Get(VanillaBuffNames.Contraption.tntIgnited);
            public static readonly NamespaceID tntCharged = Get(VanillaBuffNames.Contraption.tntCharged);
            public static readonly NamespaceID sacrificed = Get(VanillaBuffNames.Contraption.sacrificed);
            public static readonly NamespaceID magichestInvincible = Get(VanillaBuffNames.Contraption.magichestInvincible);
            public static readonly NamespaceID frankensteinShocked = Get(VanillaBuffNames.Contraption.frankensteinShocked);
            public static readonly NamespaceID dreamKeyShield = Get(VanillaBuffNames.Contraption.dreamKeyShield);

            // Chapter 2
            public static readonly NamespaceID nocturnal = Get(VanillaBuffNames.Contraption.nocturnal);
            public static readonly NamespaceID carriedByLilyPad = Get(VanillaBuffNames.Contraption.carriedByLilyPad);
            public static readonly NamespaceID carryingOther = Get(VanillaBuffNames.Contraption.carryingOther);
            public static readonly NamespaceID lilyPadEvocation = Get(VanillaBuffNames.Contraption.lilyPadEvocation);
            public static readonly NamespaceID dreamButterflyShield = Get(VanillaBuffNames.Contraption.dreamButterflyShield);
            public static readonly NamespaceID darkMatterProduction = Get(VanillaBuffNames.Contraption.darkMatterProduction);
            public static readonly NamespaceID vortexHopperSpin = Get(VanillaBuffNames.Contraption.vortexHopperSpin);
            public static readonly NamespaceID vortexHopperEvoked = Get(VanillaBuffNames.Contraption.vortexHopperEvoked);
            public static readonly NamespaceID dreamCrystalEvocation = Get(VanillaBuffNames.Contraption.dreamCrystalEvocation);
            public static readonly NamespaceID dreamSilk = Get(VanillaBuffNames.Contraption.dreamSilk);
            public static readonly NamespaceID bottledBlackholeDamage = Get(VanillaBuffNames.Contraption.bottledBlackholeDamage);

            // Chapter 3
            public static readonly NamespaceID stoneShieldProtected = Get(VanillaBuffNames.Contraption.stoneShieldProtected);
            public static readonly NamespaceID glowstoneProtected = Get(VanillaBuffNames.Contraption.glowstoneProtected);
            public static readonly NamespaceID ironCurtain = Get(VanillaBuffNames.Contraption.ironCurtain);
            public static readonly NamespaceID miracleMalletReplicaDamage = Get(VanillaBuffNames.Contraption.miracleMalletReplicaDamage);
            public static readonly NamespaceID witherSkeletonSkullReduceHealth = Get(VanillaBuffNames.Contraption.witherSkeletonSkullReduceHealth);
            public static readonly NamespaceID brokenLantern = Get(VanillaBuffNames.Contraption.brokenLantern);

            // Chapter 4
            public static readonly NamespaceID eyeOfTheGiant = Get(VanillaBuffNames.Contraption.eyeOfTheGiant);
            public static readonly NamespaceID noteBlockLoud = Get(VanillaBuffNames.Contraption.noteBlockLoud);
            public static readonly NamespaceID lightningOrbEvoked = Get(VanillaBuffNames.Contraption.lightningOrbEvoked);
            public static readonly NamespaceID devourerInvincible = Get(VanillaBuffNames.Contraption.devourerInvincible);
            public static readonly NamespaceID hellfireCursed = Get(VanillaBuffNames.Contraption.hellfireCursed);
            public static readonly NamespaceID imitated = Get(VanillaBuffNames.Contraption.imitated);
            public static readonly NamespaceID noteBlockCharged = Get(VanillaBuffNames.Contraption.noteBlockCharged);

            // Chapter 5
            public static readonly NamespaceID fireworkDispenserEvoked = Get(VanillaBuffNames.Contraption.fireworkDispenserEvoked);
            public static readonly NamespaceID hfpdUpgraded = Get(VanillaBuffNames.Contraption.hfpdUpgraded);
            public static readonly NamespaceID stolenByUFO = Get(VanillaBuffNames.Contraption.stolenByUFO);
            public static readonly NamespaceID woodenFanBlow = Get(VanillaBuffNames.Contraption.woodenFanBlow);
            public static readonly NamespaceID elasticCloudBounceCooldown = Get(VanillaBuffNames.Contraption.elasticCloudBounceCooldown);
            public static readonly NamespaceID elasticCloudEvocation = Get(VanillaBuffNames.Contraption.elasticCloudEvocation);
            public static readonly NamespaceID skywardBeaconNight = Get(VanillaBuffNames.Contraption.skywardBeaconNight);
        }
        public static class Enemy
        {
            // Difficulty
            public static readonly NamespaceID hardEnemy = Get(VanillaBuffNames.Enemy.hardEnemy);

            // Core
            public static readonly NamespaceID randomEnemySpeed = Get(VanillaBuffNames.Enemy.randomEnemySpeed);

            // Prologue
            public static readonly NamespaceID gemCarrier = Get(VanillaBuffNames.Enemy.gemCarrier);

            // Chapter 1
            public static readonly NamespaceID punchtonAchievement = Get(VanillaBuffNames.Enemy.punchtonAchievement);
            public static readonly NamespaceID starshardCarrier = Get(VanillaBuffNames.Enemy.starshardCarrier);
            public static readonly NamespaceID redstoneCarrier = Get(VanillaBuffNames.Enemy.redstoneCarrier);
            public static readonly NamespaceID ghost = Get(VanillaBuffNames.Enemy.ghost);
            public static readonly NamespaceID stun = Get(VanillaBuffNames.Enemy.stun);
            public static readonly NamespaceID minigameEnemySpeed = Get(VanillaBuffNames.Enemy.minigameEnemySpeed);
            public static readonly NamespaceID napstablookAngry = Get(VanillaBuffNames.Enemy.napstablookAngry);
            public static readonly NamespaceID frankensteinTransformer = Get(VanillaBuffNames.Enemy.frankensteinTransformer);

            // Chapter 2
            public static readonly NamespaceID boat = Get(VanillaBuffNames.Enemy.boat);
            public static readonly NamespaceID spiderClimb = Get(VanillaBuffNames.Enemy.spiderClimb);
            public static readonly NamespaceID motherTerrorLaid = Get(VanillaBuffNames.Enemy.motherTerrorLaid);
            public static readonly NamespaceID terrorParasitized = Get(VanillaBuffNames.Enemy.terrorParasitized);
            public static readonly NamespaceID gravityPadGravity = Get(VanillaBuffNames.Enemy.gravityPadGravity);
            public static readonly NamespaceID vortexHopperDrag = Get(VanillaBuffNames.Enemy.vortexHopperDrag);
            public static readonly NamespaceID fly = Get(VanillaBuffNames.Enemy.fly);
            public static readonly NamespaceID enemyWeakness = Get(VanillaBuffNames.Enemy.enemyWeakness);
            public static readonly NamespaceID forcePadDrag = Get(VanillaBuffNames.Enemy.forcePadDrag);
            public static readonly NamespaceID nightmareComeTrue = Get(VanillaBuffNames.Enemy.nightmareComeTrue);
            public static readonly NamespaceID NightmareMaskEvade = Get(VanillaBuffNames.Enemy.NightmareMaskEvade);
            public static readonly NamespaceID WitherHeartShieldResistanceBuff = Get(VanillaBuffNames.Enemy.WitherHeartShieldResistanceBuff);
            public static readonly NamespaceID LeftHandBowBuff = Get(VanillaBuffNames.Enemy.LeftHandBowBuff);

            // Chapter 3
            public static readonly NamespaceID littleZombie = Get(VanillaBuffNames.Enemy.littleZombie);
            public static readonly NamespaceID bigTrouble = Get(VanillaBuffNames.Enemy.bigTrouble);
            public static readonly NamespaceID soulsandSummoned = Get(VanillaBuffNames.Enemy.soulsandSummoned);
            public static readonly NamespaceID seijaMesmerizer = Get(VanillaBuffNames.Enemy.seijaMesmerizer);
            public static readonly NamespaceID beingRiden = Get(VanillaBuffNames.Enemy.beingRiden);
            public static readonly NamespaceID ridingPassenger = Get(VanillaBuffNames.Enemy.ridingPassenger);

            // Chapter 4
            public static readonly NamespaceID wickedHermitWarp = Get(VanillaBuffNames.Enemy.wickedHermitWarp);
            public static readonly NamespaceID wickedHermitWarpped = Get(VanillaBuffNames.Enemy.wickedHermitWarpped);
            public static readonly NamespaceID necrotombstoneRising = Get(VanillaBuffNames.Enemy.necrotombstoneRising);
            public static readonly NamespaceID slow = Get(VanillaBuffNames.Enemy.slow);
            public static readonly NamespaceID iZombieAttackBooster = Get(VanillaBuffNames.Enemy.iZombieAttackBooster);
            public static readonly NamespaceID iZombieImp = Get(VanillaBuffNames.Enemy.iZombieImp);
            public static readonly NamespaceID iZombieSkeletonWarrior = Get(VanillaBuffNames.Enemy.iZombieSkeletonWarrior);
            public static readonly NamespaceID shikaisenRevive = Get(VanillaBuffNames.Enemy.shikaisenRevive);

            // Chapter 5
            public static readonly NamespaceID paratroop = Get(VanillaBuffNames.Enemy.paratroop);
            public static readonly NamespaceID summonedByUFO = Get(VanillaBuffNames.Enemy.summonedByUFO);
            public static readonly NamespaceID ufoBlueAbsorb = Get(VanillaBuffNames.Enemy.ufoBlueAbsorb);
            public static readonly NamespaceID heavyCannon = Get(VanillaBuffNames.Enemy.heavyCannon);
            public static readonly NamespaceID waterStainSlide = Get(VanillaBuffNames.Enemy.waterStainSlide);

            public static readonly NamespaceID blownByWoodenFan = Get(VanillaBuffNames.Enemy.blownByWoodenFan);
            public static readonly NamespaceID lunaticEnemy = Get(VanillaBuffNames.Enemy.lunaticEnemy);






            //EXPAND
            public static readonly NamespaceID AntiGravityPadGravity = Get(VanillaBuffNames.Enemy.AntiGravityPadGravity);
            public static readonly NamespaceID Shock = Get(VanillaBuffNames.Enemy.Shock);
            public static readonly NamespaceID AttackSpeed = Get(VanillaBuffNames.Enemy.AttackSpeed);
            public static readonly NamespaceID SoulFreeze = Get(VanillaBuffNames.Enemy.SoulFreeze);


        }
        public static class Obstacle
        {
        }
        public static class Boss
        {
            public static readonly NamespaceID bossRevenge = Get(VanillaBuffNames.Boss.bossRevenge);
            // Chapter 1
            public static readonly NamespaceID frankensteinSteel = Get(VanillaBuffNames.Boss.frankensteinSteel);
            public static readonly NamespaceID frankensteinTransforming = Get(VanillaBuffNames.Boss.frankensteinTransforming);

            // Chapter 2
            public static readonly NamespaceID nightmareaperFall = Get(VanillaBuffNames.Boss.nightmareaperFall);
            public static readonly NamespaceID nightmareaperEnraged = Get(VanillaBuffNames.Boss.nightmareaperEnraged);

            // Chapter 3
            public static readonly NamespaceID seijaFabric = Get(VanillaBuffNames.Boss.seijaFabric);
            public static readonly NamespaceID seijaGap = Get(VanillaBuffNames.Boss.seijaGap);

            // Chapter 4
            public static readonly NamespaceID theGiantInactive = Get(VanillaBuffNames.Boss.theGiantInactive);
            public static readonly NamespaceID theGiantPacman = Get(VanillaBuffNames.Boss.theGiantPacman);
            public static readonly NamespaceID theGiantPacmanKilled = Get(VanillaBuffNames.Boss.theGiantPacmanKilled);
            public static readonly NamespaceID theGiantSnake = Get(VanillaBuffNames.Boss.theGiantSnake);
            public static readonly NamespaceID theGiantPhase3 = Get(VanillaBuffNames.Boss.theGiantPhase3);
        }
        public static class Cart
        {
            // Prologue
            public static readonly NamespaceID cartFadeIn = Get(VanillaBuffNames.Cart.cartFadeIn);
        }
        public static class Pickup
        {
            // Chapter 5
            public static readonly NamespaceID absorbedByUFO = Get(VanillaBuffNames.Pickup.absorbedByUFO);
        }
        public static class Projectile
        {
            // Chapter 1
            public static readonly NamespaceID projectileWait = Get(VanillaBuffNames.Projectile.projectileWait);


            // Chapter 2
            public static readonly NamespaceID projectileKnockback = Get(VanillaBuffNames.Projectile.projectileKnockback);
            public static readonly NamespaceID ghastFireCharge = Get(VanillaBuffNames.Projectile.ghastFireCharge);

            // Chapter 3
            public static readonly NamespaceID invertedMirror = Get(VanillaBuffNames.Projectile.invertedMirror);

            // Chapter 4
            public static readonly NamespaceID hellfireIgnited = Get(VanillaBuffNames.Projectile.hellfireIgnited);

            // Chapter 5
            public static readonly NamespaceID beaconMeteorNoDestroy = Get(VanillaBuffNames.Projectile.beaconMeteorNoDestroy);
        }
        public static class Effect
        {
            // Chapter 2
            public static readonly NamespaceID breakoutBoardUpgrade = Get(VanillaBuffNames.Effect.breakoutBoardUpgrade);

            // Chapter 5
            public static readonly NamespaceID waterStainFrozen = Get(VanillaBuffNames.Effect.waterStainFrozen);
        }

        public static class SeedPack
        {
            // Difficulty
            public static readonly NamespaceID easyBlueprint = Get(VanillaBuffNames.SeedPack.easyBlueprint);

            // Stages
            public static readonly NamespaceID tutorialDisable = Get(VanillaBuffNames.SeedPack.tutorialBlueprintDisable);
            public static readonly NamespaceID upgradeEndlessCost = Get(VanillaBuffNames.SeedPack.upgradeEndlessCost);

            // Chapter 1
            public static readonly NamespaceID theCreaturesHeartReduceCost = Get(VanillaBuffNames.SeedPack.theCreaturesHeartReduceCost);

            // Chapter 2
            public static readonly NamespaceID slendermanMindSwap = Get(VanillaBuffNames.SeedPack.slendermanMindSwap);

            // Chapter 3
            public static readonly NamespaceID witherSkeletonSkullReduceCost = Get(VanillaBuffNames.SeedPack.witherSkeletonSkullReduceCost);

            public static readonly NamespaceID FrankensteinBrainBuff = Get(VanillaBuffNames.SeedPack.FrankensteinBrainBuff);
        }
    }
}
