#nullable enable // autogenerated

using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Obstacles;
using MVZ2.Vanilla.Entities;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Buffs;
using UnityEngine;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.Squid)]
    public class Squid : ProjectileBehaviour
    {
        public Squid(string nsp, string name) : base(nsp, name)
        {
        }

        protected override void PostHitEntity(ProjectileHitOutput hitResult, DamageOutput? damage)
        {
            base.PostHitEntity(hitResult, damage);

            if (hitResult.Shield != null)
                return;

            var other = hitResult.Other;
            if (other == null || other.Type != EntityTypes.PLANT || other.IsDead)
                return;

            // 检查是否已被标记
            if (SquidDrownedMarkedBuff.IsMarked(other))
                return;

            var level = other.Level;

            // 1. 为器械添加标记 buff（休眠 + 记录关联）
            var markBuff = other.AddBuff<SquidDrownedMarkedBuff>();
            if (markBuff != null)
            {
                // 2. 在原位置生成敌方障碍物"鱿鱼笼"
            var cage = level.Spawn(VanillaObstacleID.SquidCage, other.Position, other);
                if (cage != null)
                {
                    // 双向关联：障碍物记录器械 ID
                    SquidCageBehaviour.SetTrappedPlantID(cage, new EntityID(other));
                    // buff 记录障碍物 ID（用于器械被其他方式移除时清理障碍物）
                    SquidDrownedMarkedBuff.SetCageID(markBuff, new EntityID(cage));
                }
            }
        }
    }
}
