#nullable enable // autogenerated

using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Level;
using PVZEngine.Entities;
using UnityEngine;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.WintherMage)]
    public class WintherMage : SkeletonMage
    {
        public WintherMage(string nsp, string name) : base(nsp, name)
        {
            // 继承父类构造函数中的 detector 即可，不需要重复创建
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
        }

        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
        }
        private void UpdateTarget(Entity enemy)
        {
            if (CanShoot(enemy))
            {
                if (enemy.Target != null && !ValidateTarget(enemy, enemy.Target))
                {
                    enemy.Target = null;
                }
                enemy.Target = FindTarget(enemy);
            }
            else
            {
                enemy.Target = null;
            }
        }
        protected override void UpdateStateAttack(Entity enemy)
        {
            // 复制并稍微修改父类的逻辑，将 ATTACK_RESTORE_TIME 改为你的新值（比如 30）
            var timer = GetStateTimer(enemy);
            if (timer == null)
                return;

            timer.Run(enemy.GetAttackSpeed());
            if (timer.Expired)
            {
                var attackState = GetAttackState(enemy);
                if (attackState == ATTACK_STATE_FIRE)
                {
                    SetAttackState(enemy, ATTACK_STATE_RESTORE);
                    // 这里使用新的时间，比如 30
                    timer.ResetTime(90);
                    Shoot(enemy);
                }
                else if (attackState == ATTACK_STATE_RESTORE)
                {
                    UpdateTarget(enemy);
                    SetAttackState(enemy, ATTACK_STATE_CAST);
                    timer.ResetTime(ATTACK_CAST_TIME);
                }
            }
        }

        protected override void Shoot(Entity enemy)
        {
            // 在父类逻辑中，当 timer 过期且状态为 ATTACK_STATE_FIRE 时，会触发 Shoot。
            // 我们只需要在这里 override 发射逻辑。

            // 每4次射击，召唤一次流星
            if (shoot_times < 4)
            {
                var param = enemy.GetShootParams();
                param.damage = enemy.GetDamage() * 4f;          // 4倍的伤害
                param.projectileID = VanillaProjectileID.witherSkull; // 凋灵头颅
                param.soundID = VanillaSoundID.fire;           // 音效
                enemy.ShootProjectile(param);

                // 射击次数 +1
                shoot_times += 1;
            }

            // 每4次射击结束后，召唤一次流星
            if (shoot_times >= 4)
            {
                var target = FindTarget(enemy);
                if (target != null)
                {
                    var pos = target.GetCenter() + new Vector3(0, 1280, 0); // 在目标正上方生成
                    var meteor = enemy.SpawnWithParams(VanillaEffectID.cursedMeteor, pos);
                    if (meteor != null)
                    {
                        meteor.SetParent(enemy);
                        meteor.PlaySound(VanillaSoundID.bombFalling);
                    }
                }
                // 重置计数器
                shoot_times = 0;
            }
        }

        private int shoot_times = 0;

        public const int VARIANT_RANDOM = 0;
        public const int VARIANT_FIRE = 1;
        public const int VARIANT_FROST = 2;
        public const int VARIANT_LIGHTNING = 3;
        public static int[] mageVariants = new int[]
        {
            SkeletonMage.VARIANT_LIGHTNING // 仅保留闪电
        };
    }
}