#nullable enable // autogenerated

using MVZ2.GameContent.Buffs;
using MVZ2.GameContent.Enemies;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.SquidDrowned)]
    public class SquidDrowned : AIEntityBehaviour
    {
        public SquidDrowned(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetSkillCooldown(entity, 0f);
        }

        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);

            // 被魅惑或死亡时不行动
            if (entity.IsCharmed() || entity.IsDead)
                return;

            // 冷却计时
            var cooldown = GetSkillCooldown(entity);
            if (cooldown > 0)
            {
                SetSkillCooldown(entity, cooldown - entity.GetAttackSpeed());
            }

            // 冷却未结束，不释放技能
            if (GetSkillCooldown(entity) > 0)
                return;

            // 查找最近的器械目标
            var target = FindNearestPlantTarget(entity);
            if (target == null)
                return;

            // 已被标记的目标跳过
            if (SquidDrownedMarkedBuff.IsMarked(target))
                return;

            // 释放技能
            ShootSquid(entity, target);
            SetSkillCooldown(entity, SKILL_COOLDOWN);
        }

        private static Entity? FindNearestPlantTarget(Entity self)
        {
            var level = self.Level;
            var myLane = self.GetLane();
            Entity? nearest = null;
            float nearestDist = float.MaxValue;

            // 搜索所有器械
            var plants = level.FindEntities(e => 
                e.Type == EntityTypes.PLANT && 
                !e.IsDead && 
                self.IsHostile(e) &&
                !SquidDrownedMarkedBuff.IsMarked(e));

            foreach (var plant in plants)
            {
                var dist = Mathf.Abs(plant.Position.x - self.Position.x);
                // 优先选择同车道的
                var laneBonus = (plant.GetLane() == myLane) ? 0f : 100f;
                var totalDist = dist + laneBonus;

                if (totalDist < nearestDist)
                {
                    nearestDist = totalDist;
                    nearest = plant;
                }
            }

            return nearest;
        }

        private static void ShootSquid(Entity entity, Entity target)
        {
            var source = entity.GetShootPoint();
            var targetPos = target.GetCenter();
            var velocity = VanillaProjectileExt.GetLobVelocityByTime(source, targetPos, 30f, entity.GetGravity());

            var param = entity.GetShootParams();
            param.projectileID = VanillaProjectileID.Squid;
            param.position = source;
            param.velocity = velocity;

            var projectile = entity.ShootProjectile(param);
            if (projectile != null)
            {
                projectile.SetDamage(0);
            }
        }

        public static float GetSkillCooldown(Entity entity) => entity.GetBehaviourField<float>(ID, PROP_SKILL_COOLDOWN);
        public static void SetSkillCooldown(Entity entity, float value) => entity.SetBehaviourField(ID, PROP_SKILL_COOLDOWN, Mathf.Max(0, value));

        private static readonly NamespaceID ID = VanillaEnemyID.SquidDrowned;
        public static readonly VanillaEntityPropertyMeta<float> PROP_SKILL_COOLDOWN = new VanillaEntityPropertyMeta<float>("SkillCooldown");
        public const float SKILL_COOLDOWN = 480f; // 8秒冷却
    }
}
