#nullable enable // autogenerated

using MVZ2.Vanilla;
using PVZEngine;

namespace MVZ2.GameContent.Projectiles
{
    public static class VanillaProjectileNames
    {
        public const string arrow = "arrow";
        public const string mineTNTSeed = "mine_tnt_seed";
        public const string snowball = "snowball";
        public const string largeSnowball = "large_snowball";
        public const string flyingTNT = "flying_tnt";
        public const string soulfireBall = "soulfire_ball";
        public const string spiceGas = "spice_gas";
        public const string knife = "knife";
        public const string bullet = "bullet";
        public const string missile = "missile";

        public const string largeArrow = "large_arrow";
        public const string breakoutPearl = "breakout_pearl";
        public const string spike = "spike";
        public const string spikeBall = "spike_ball";
        public const string parabot = "parabot";
        public const string fireCharge = "fire_charge";
        public const string dart = "dart";
        public const string poisonJavelin = "poison_javelin";
        public const string weaknessGas = "weakness_gas";

        public const string woodenBall = "wooden_ball";
        public const string cobble = "cobble";
        public const string boulder = "boulder";
        public const string goldenBall = "golden_ball";
        public const string diamondCaltrop = "diamond_caltrop";
        public const string compellingOrb = "compelling_orb";
        public const string seijaMagicBomb = "seija_magic_bomb";
        public const string seijaBullet = "seija_bullet";
        public const string witherSkull = "wither_skull";

        public const string crossbowBolt = "crossbow_bolt";
        public const string reflectionBullet = "reflection_bullet";
        public const string note = "note";
        public const string fireball = "fireball";
        public const string iceBolt = "ice_bolt";
        public const string chargedBolt = "charged_bolt";

        public const string hellPlanetOtherworld = "hell_planet_otherworld";
        public const string hellPlanetEarth = "hell_planet_earth";
        public const string hellPlanetMoon = "hell_planet_moon";
        public const string shuriken = "shuriken";
        public const string beaconMeteor = "beacon_meteor";
        public const string firework = "firework";
        public const string fireworkBig = "firework_big";
        public const string fallingStar = "falling_star";
        public const string explosiveLargeFireball = "explosive_large_fireball";

        //EXPAND
        public const string purpleArrow = "purpleArrow";
        public const string ObsidianShard = "ObsidianShard";
        public const string Poisonball = "Poisonball";
        public const string largePoisonball = "largePoisonball";
        public const string RedKnife = "RedKnife";
        public const string CopperBall = "CopperBall";
        public const string CopperOreBall = "CopperOreBall";
        public const string PulseArrow = "PulseArrow";
        public const string NightmareBall = "NightmareBall";
        public const string IcedBolt = "IcedBolt";
        public const string BloodBolt = "BloodBolt";
        public const string BigFireCharge = "BigFireCharge";
        public const string SmallRocket = "SmallRocket";
        public const string Squid = "Squid";
    }
    public static class VanillaProjectileID
    {
        public static readonly NamespaceID arrow = Get(VanillaProjectileNames.arrow);
        public static readonly NamespaceID mineTNTSeed = Get(VanillaProjectileNames.mineTNTSeed);
        public static readonly NamespaceID snowball = Get(VanillaProjectileNames.snowball);
        public static readonly NamespaceID largeSnowball = Get(VanillaProjectileNames.largeSnowball);
        public static readonly NamespaceID flyingTNT = Get(VanillaProjectileNames.flyingTNT);
        public static readonly NamespaceID soulfireBall = Get(VanillaProjectileNames.soulfireBall);
        public static readonly NamespaceID spiceGas = Get(VanillaProjectileNames.spiceGas);
        public static readonly NamespaceID knife = Get(VanillaProjectileNames.knife);

        public static readonly NamespaceID bullet = Get(VanillaProjectileNames.bullet);
        public static readonly NamespaceID missile = Get(VanillaProjectileNames.missile);

        public static readonly NamespaceID largeArrow = Get(VanillaProjectileNames.largeArrow);
        public static readonly NamespaceID breakoutPearl = Get(VanillaProjectileNames.breakoutPearl);
        public static readonly NamespaceID spike = Get(VanillaProjectileNames.spike);
        public static readonly NamespaceID spikeBall = Get(VanillaProjectileNames.spikeBall);
        public static readonly NamespaceID parabot = Get(VanillaProjectileNames.parabot);
        public static readonly NamespaceID fireCharge = Get(VanillaProjectileNames.fireCharge);
        public static readonly NamespaceID dart = Get(VanillaProjectileNames.dart);
        public static readonly NamespaceID poisonJavelin = Get(VanillaProjectileNames.poisonJavelin);
        public static readonly NamespaceID weaknessGas = Get(VanillaProjectileNames.weaknessGas);

        public static readonly NamespaceID woodenBall = Get(VanillaProjectileNames.woodenBall);
        public static readonly NamespaceID cobble = Get(VanillaProjectileNames.cobble);
        public static readonly NamespaceID boulder = Get(VanillaProjectileNames.boulder);
        public static readonly NamespaceID goldenBall = Get(VanillaProjectileNames.goldenBall);
        public static readonly NamespaceID diamondCaltrop = Get(VanillaProjectileNames.diamondCaltrop);
        public static readonly NamespaceID compellingOrb = Get(VanillaProjectileNames.compellingOrb);
        public static readonly NamespaceID seijaMagicBomb = Get(VanillaProjectileNames.seijaMagicBomb);
        public static readonly NamespaceID seijaBullet = Get(VanillaProjectileNames.seijaBullet);
        public static readonly NamespaceID witherSkull = Get(VanillaProjectileNames.witherSkull);

        public static readonly NamespaceID crossbowBolt = Get(VanillaProjectileNames.crossbowBolt);
        public static readonly NamespaceID reflectionBullet = Get(VanillaProjectileNames.reflectionBullet);
        public static readonly NamespaceID note = Get(VanillaProjectileNames.note);
        public static readonly NamespaceID fireball = Get(VanillaProjectileNames.fireball);
        public static readonly NamespaceID iceBolt = Get(VanillaProjectileNames.iceBolt);
        public static readonly NamespaceID chargedBolt = Get(VanillaProjectileNames.chargedBolt);

        public static readonly NamespaceID hellPlanetOtherworld = Get(VanillaProjectileNames.hellPlanetOtherworld);
        public static readonly NamespaceID hellPlanetEarth = Get(VanillaProjectileNames.hellPlanetEarth);
        public static readonly NamespaceID hellPlanetMoon = Get(VanillaProjectileNames.hellPlanetMoon);
        public static readonly NamespaceID shuriken = Get(VanillaProjectileNames.shuriken);
        public static readonly NamespaceID beaconMeteor = Get(VanillaProjectileNames.beaconMeteor);
        public static readonly NamespaceID firework = Get(VanillaProjectileNames.firework);
        public static readonly NamespaceID fireworkBig = Get(VanillaProjectileNames.fireworkBig);
        public static readonly NamespaceID fallingStar = Get(VanillaProjectileNames.fallingStar);
        public static readonly NamespaceID explosiveLargeFireball = Get(VanillaProjectileNames.explosiveLargeFireball);

        //EXPAND
        public static readonly NamespaceID purpleArrow = Get(VanillaProjectileNames.purpleArrow);
        public static readonly NamespaceID ObsidianShard = Get(VanillaProjectileNames.ObsidianShard);
        public static readonly NamespaceID RedKnife = Get(VanillaProjectileNames.RedKnife);
        public static readonly NamespaceID Poisonball = Get(VanillaProjectileNames.Poisonball);
        public static readonly NamespaceID largePoisonball = Get(VanillaProjectileNames.largePoisonball);
        public static readonly NamespaceID CopperBall = Get(VanillaProjectileNames.CopperBall);
        public static readonly NamespaceID CopperOreBall = Get(VanillaProjectileNames.CopperOreBall);
        public static readonly NamespaceID PulseArrow = Get(VanillaProjectileNames.PulseArrow);
        public static readonly NamespaceID NightmareBall = Get(VanillaProjectileNames.NightmareBall);
        public static readonly NamespaceID IcedBolt = Get(VanillaProjectileNames.IcedBolt);
        public static readonly NamespaceID BloodBolt = Get(VanillaProjectileNames.BloodBolt);
        public static readonly NamespaceID BigFireCharge = Get(VanillaProjectileNames.BigFireCharge);
        public static readonly NamespaceID SmallRocket = Get(VanillaProjectileNames.SmallRocket);
        public static readonly NamespaceID Squid = Get(VanillaProjectileNames.Squid);

        private static NamespaceID Get(string name)
        {
            return new NamespaceID(VanillaMod.spaceName, name);
        }
    }
}
