#nullable enable // autogenerated

using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using System.Collections.Generic;
using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Effects;
using MVZ2Logic.Level;
using MVZ2Logic.SeedPacks;
using PVZEngine;
using PVZEngine.Buffs;
using UnityEngine;
using MVZ2.GameContent.Bosses;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.NightmareDisciple)]
    public class NightmareDisciple : SkeletonMage
    {
        public NightmareDisciple(string nsp, string name) : base(nsp, name)
        {
            // 继承父类的 detector 即可
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.SetAnimationInt("Variant", entity.GetVariant());
            entity.SetBehaviourField(ID, PROP_PORTAL_TIMER, new FrameTimer(PORTAL_COOLDOWN));

            // 检查是否存活 Boss，添加 Buff
            var level = entity.Level;
            var hasAliveBoss = entity.Level.EntityExists(e => e != entity && (e.IsEntityOf(VanillaBossID.slenderman) || e.IsEntityOf(VanillaBossID.nightmareaper)) && !e.IsDead);

            if (hasAliveBoss)
            {
                if (!entity.HasBuff<VanguardResistanceBuff>())
                {
                    entity.AddBuff<VanguardResistanceBuff>();
                }
            }
        }

        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity); // 这里会调用父类的基础状态机
            PortalUpdate(entity);  // 加上你的专属 Portal 逻辑
        }

        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            entity.SetAnimationInt("Variant", entity.GetVariant());
        }

        private void UpdateTarget(Entity enemy)
        {
            if (CanShoot(enemy))
            {
                if (enemy.Target != null && !ValidateTarget(enemy, enemy.Target))
                {
                    enemy.Target = null;
                }
                enemy.Target = FindTarget(enemy);
            }
            else
            {
                enemy.Target = null;
            }
        }
        // 重点：为了让你的 ATTACK_RESTORE_TIME_OWN 生效，必须重写这个方法并修改计时器
        protected override void UpdateStateAttack(Entity enemy)
        {
            var timer = GetStateTimer(enemy);
            if (timer == null)
                return;

            timer.Run(enemy.GetAttackSpeed());
            if (timer.Expired)
            {
                var attackState = GetAttackState(enemy);
                if (attackState == ATTACK_STATE_FIRE)
                {
                    SetAttackState(enemy, ATTACK_STATE_RESTORE);
                    timer.ResetTime(ATTACK_RESTORE_TIME_OWN);
                    Shoot(enemy);
                }
                else if (attackState == ATTACK_STATE_RESTORE)
                {
                    UpdateTarget(enemy);
                    SetAttackState(enemy, ATTACK_STATE_CAST);
                    timer.ResetTime(ATTACK_CAST_TIME);
                }
            }
        }

        protected override void Shoot(Entity enemy)
        {
            var enemyClass = enemy.GetVariant();
            switch (enemyClass)
            {
                case VARIANT_FROST:
                case VARIANT_LIGHTNING:
                    {
                        var param = enemy.GetShootParams();
                        param.damage = enemy.GetDamage() * 0.1f;
                        param.projectileID = VanillaProjectileID.BloodBolt;
                        param.soundID = VanillaSoundID.snow;
                        enemy.ShootProjectile(param);
                    }
                    break;
                default:
                    {
                        var param = enemy.GetShootParams();
                        param.damage = enemy.GetDamage() * 0.4f;
                        param.projectileID = VanillaProjectileID.NightmareBall;
                        param.soundID = VanillaSoundID.fire;
                        enemy.ShootProjectile(param);
                    }
                    break;
            }
        }

        #region Portal
        private void PortalUpdate(Entity entity)
        {
            var portalTimer = GetPortalTimer(entity);
            if (portalTimer.RunToExpiredAndNotNull())
            {
                portalTimer.Reset();
                CreatePortals(entity);
            }
        }

        private void CreatePortals(Entity entity)
        {
            var level = entity.Level;
            List<Vector2Int> placePool = new List<Vector2Int>();

            int maxColumnCount = level.GetMaxColumnCount();
            int maxRowCount = level.GetMaxLaneCount();
            for (int c = maxColumnCount - 2; c < maxColumnCount; c++)
            {
                for (int r = 0; r < maxRowCount; r++)
                {
                    placePool.Add(new Vector2Int(c, r));
                }
            }
            var portalRNG = entity.RNG;
            if (portalRNG != null)
            {
                for (int i = 0; i < 3; i++)
                {
                    var enemyID = GetRandomPortalEnemyID(portalRNG);
                    var index = portalRNG.Next(0, placePool.Count);
                    Vector2Int place = placePool[index];
                    placePool.Remove(place);

                    var x = level.GetEntityColumnX(place.x);
                    var z = level.GetEntityLaneZ(place.y);
                    var y = level.GetGroundY(x, z);
                    Vector3 pos = new Vector3(x, y, z);
                    SpawnPortal(entity, pos, enemyID);
                }
                entity.PlaySound(VanillaSoundID.nightmarePortal);
            }
        }
        private Entity? SpawnPortal(Entity boss, Vector3 position, NamespaceID enemyID)
        {
            return boss.SpawnWithParams(VanillaEffectID.nightmarePortal, position)?.Let(e =>
            {
                NightmarePortal.SetEnemyID(e, enemyID);
            });
        }
        private NamespaceID GetRandomPortalEnemyID(RandomGenerator rng)
        {
            var index = rng.WeightedRandom(portalPoolWeights);
            return portalPool[index];
        }

        private static NamespaceID[] portalPool = new NamespaceID[]
        {
            VanillaEnemyID.zombie,
            VanillaEnemyID.leatherCappedZombie,
            VanillaEnemyID.HostZombie,
            VanillaEnemyID.ironHelmettedZombie,
            VanillaEnemyID.flagZombie,

        };

        private static int[] portalPoolWeights = new int[]
        {
            20,
            10,
            10,
            5,
            1
        };
        #endregion


        public static FrameTimer? GetPortalTimer(Entity boss) => boss.GetBehaviourField<FrameTimer>(ID, PROP_PORTAL_TIMER);

        public const int ATTACK_RESTORE_TIME_OWN = 20; // 你自定义的攻击间隔

        private static readonly NamespaceID ID = VanillaEnemyID.NightmareDisciple;
        private static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_PORTAL_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("PortalTimer");

        public const int PORTAL_COOLDOWN = 180;
        public static int[] mageVariants = new int[]
        {
            NightmareDisciple.VARIANT_FIRE,
            NightmareDisciple.VARIANT_FROST,
            NightmareDisciple.VARIANT_LIGHTNING
        };
    }
}